server:
  port: 9797

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://120.78.222.109:3306/inm_villa?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: inmoods
    password: Inmoods@2016

# MyBatisPlus的相关配置
mybatis-plus:
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    # 打印sql语句，将mybatis-plus自带的SQL打印注释，使用logback记录日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除字段
  global-config:
    db-config:
      # 删除状态为1(true)
      logic-delete-value: true
      # 没有删除状态为0(false)
      logic-not-delete-value: false
