server:
  port: 9797

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  #redis配置
  redis:
    # 地址
    host: localhost
    #端口
    port: 6379
    #数据库索引
    database: 0
    #密码
    password:
    #连接超时时间
    timeout: 10s
    lettuce:
      pool:
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池的最大数据库连接数
        max-active: 8
        ##连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# MyBatisPlus的相关配置
mybatis-plus:
  mapperLocations: classpath*:com.vietnam.lottery/business/**/mapper/*.xml
  typeAliasesPackage: com.vietnam.lottery.business.*.entity
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    # 打印sql语句，将mybatis-plus自带的SQL打印注释，使用logback记录日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除字段
  global-config:
    db-config:
      # 删除状态为1(true)
      logic-delete-value: true
      # 没有删除状态为0(false)
      logic-not-delete-value: false

#jwt
jwt:
  header: authorization
  tokenPrefix: Bearer
  secret: vietnamLottery202201241022
  expireTime: 10080

